#!/usr/bin/env python3
"""Score source-level recovery facts in generated Clutter IR."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def load_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as source:
        return json.load(source)


def stale_reasons(output: Path, running_version: str | None) -> list[str]:
    """Reports why a generated output may predate the current tool build.

    Stored matrices silently fail after any renderer change that alters
    expression text (probe EC-10). The manifest carries the tool version and
    the exact input hash, so an output produced by a different binary than
    the one now installed is flagged up front instead of failing deep inside
    semantic matching.
    """
    reasons: list[str] = []
    manifest_path = output / "decompilation.json"
    if not manifest_path.exists():
        return [f"missing {manifest_path}"]
    manifest = load_json(manifest_path)
    generated_version = manifest.get("tool_version")
    if running_version and generated_version != running_version:
        reasons.append(
            f"generated by clutter {generated_version}, "
            f"running clutter {running_version}"
        )
    stamp_path = output / ".clutter-render-stamp"
    if stamp_path.exists() and manifest_path.stat().st_mtime < stamp_path.stat().st_mtime:
        # A newer binary touched this workspace without regenerating it.
        reasons.append("binary is newer than the generated output")
    return reasons


def parse_variant(value: str) -> tuple[str, Path]:
    name, separator, path = value.partition("=")
    if not separator or not name or not path:
        raise argparse.ArgumentTypeError("variant must be NAME=OUTPUT_DIRECTORY")
    return name, Path(path)


def matching_statements(program: dict, expected: dict) -> list[dict]:
    matches = []
    for function in program.get("functions", []):
        if "function" in expected and function.get("name") != expected["function"]:
            continue
        if "owner" in expected and function.get("owner") != expected["owner"]:
            continue
        for statement in function.get("semantic_statements", []):
            if statement.get("kind") != expected["kind"]:
                continue
            if any(
                statement.get(field) != expected[field]
                for field in ("expression", "target", "arguments")
                if field in expected
            ):
                continue
            matches.append(
                {
                    "owner": function.get("owner"),
                    "function": function.get("name"),
                    "address": function.get("address"),
                    "statement_address": statement.get("address"),
                }
            )
    return matches


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--expectations",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "accuracy_expectations.json",
    )
    parser.add_argument(
        "--variant",
        action="append",
        type=parse_variant,
        required=True,
        help="generated output as NAME=OUTPUT_DIRECTORY; repeat for each build",
    )
    parser.add_argument(
        "--allow-partial",
        action="store_true",
        help="score only supplied variants instead of requiring the full expectation matrix",
    )
    parser.add_argument(
        "--clutter-version",
        default=None,
        help="version of the clutter binary that generated the supplied outputs; "
        "mismatches are reported as staleness warnings (probe EC-10)",
    )
    arguments = parser.parse_args()

    expectations = load_json(arguments.expectations)
    variant_names = [name for name, _ in arguments.variant]
    duplicates = sorted({name for name in variant_names if variant_names.count(name) > 1})
    if duplicates:
        parser.error(f"duplicate variant(s): {', '.join(duplicates)}")
    supplied = dict(arguments.variant)
    expected_variants = set(expectations["variants"])
    unknown = sorted(set(supplied) - expected_variants)
    if unknown:
        parser.error(f"no expectations for variant(s): {', '.join(unknown)}")
    missing = sorted(expected_variants - set(supplied))
    if missing and not arguments.allow_partial:
        parser.error(
            "missing variant(s): "
            + ", ".join(missing)
            + "; pass --allow-partial for a focused run"
        )

    report: dict[str, dict] = {"variants": {}, "semantic_statements": {}}
    stale: dict[str, list[str]] = {}
    passed = True
    programs: dict[str, dict] = {}
    for name, output in supplied.items():
        reasons = stale_reasons(output, arguments.clutter_version)
        if reasons:
            stale[name] = reasons
        manifest = load_json(output / "decompilation.json")
        program = load_json(output / "ir" / "program.json")
        programs[name] = program
        expected = expectations["variants"][name]
        package_passed = manifest.get("application_package") == expected["application_package"]
        actual_functions = len(program.get("functions", []))
        functions_passed = actual_functions >= expected["minimum_functions"]
        report["variants"][name] = {
            "application_package": {
                "expected": expected["application_package"],
                "actual": manifest.get("application_package"),
                "passed": package_passed,
            },
            "functions": {
                "minimum": expected["minimum_functions"],
                "actual": actual_functions,
                "passed": functions_passed,
            },
        }
        passed &= package_passed and functions_passed

    if stale:
        # Staleness is a loud warning, not a score change: the stored facts
        # may still hold, but a silent-fail diagnosis must start here.
        report["stale_outputs"] = stale
        print(
            "WARNING: outputs predate the current tool build; regenerate "
            "before trusting failures (probe EC-10):",
            file=sys.stderr,
        )
        for name in sorted(stale):
            print(f"  {name}: {'; '.join(stale[name])}", file=sys.stderr)

    for expected in expectations.get("semantic_statements", []):
        feature_report = {}
        for name in expected["variants"]:
            if name not in programs:
                continue
            matches = matching_statements(programs[name], expected)
            feature_report[name] = {"passed": bool(matches), "matches": matches}
            passed &= bool(matches)
        report["semantic_statements"][expected["id"]] = feature_report

    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
